<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Attendance Verify"
           tests="4"
           failures="1"
           errors="0"
           skipped="1"
           time="126.762">
  <properties />
            <testcase name="VerifyAttendanceReject" time="21.970" classname="Module.ESS.LeaveandAttendance.LeaveApplication.TC012_AttendanceVerify">
                <failure type="java.lang.AssertionError"
                  message="Attendance not rejected"
              >
<![CDATA[java.lang.AssertionError: Attendance not rejected
  org.testng.Assert.fail(Assert.java:94)
  Module.ESS.LeaveandAttendance.LeaveApplication.TC012_AttendanceVerify.VerifyAttendanceReject(TC012_AttendanceVerify.java:105)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
  org.testng.TestRunner.privateRun(TestRunner.java:773)
  org.testng.TestRunner.run(TestRunner.java:623)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
  org.testng.SuiteRunner.run(SuiteRunner.java:259)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
  org.testng.TestNG.run(TestNG.java:1018)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
      </failure>

          </testcase>
  
            <testcase name="VerifyAttendanceApprove" time="0.0" classname="Module.ESS.LeaveandAttendance.LeaveApplication.TC012_AttendanceVerify">
          <skipped />
    </testcase>
  
            <testcase name="TargetPage" time="86.555" classname="Module.ESS.LeaveandAttendance.LeaveApplication.TC012_AttendanceVerify" />
                <testcase name="Login" time="2.280" classname="Module.ESS.LeaveandAttendance.LeaveApplication.TC012_AttendanceVerify" />
      
</testsuite>
