<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="OSO-DTP-057" name="Campus Master Data Upload" tests="5" failures="1" timestamp="25 Nov 2017 13:36:13 GMT" time="90.867" errors="0">
  <testcase name="Login" time="1.087" classname="Module.HRSetup.Recruitment.TC043_CampusMasterDataUpload"/>
  <testcase name="TargetPage" time="38.548" classname="Module.HRSetup.Recruitment.TC043_CampusMasterDataUpload"/>
  <testcase name="Add_New_Button" time="3.107" classname="Module.HRSetup.Recruitment.TC043_CampusMasterDataUpload"/>
  <testcase name="Add_Allowance_Deduction_Data" time="25.784" classname="Module.HRSetup.Recruitment.TC043_CampusMasterDataUpload"/>
  <testcase name="Edit_Record" time="6.486" classname="Module.HRSetup.Recruitment.TC043_CampusMasterDataUpload">
    <failure type="java.lang.AssertionError" message="expected : [Record Updated Successfully.] but Found : [Record Updated Successfully]">
      <![CDATA[java.lang.AssertionError: expected : [Record Updated Successfully.] but Found : [Record Updated Successfully]
	at pom.TestBase.CommonMethods.Test_Edit_Record(CommonMethods.java:172)
	at pom.ObjectPages.uiActions.CampusMaster.Test_Edit_Record(CampusMaster.java:135)
	at Module.HRSetup.Recruitment.TC043_CampusMasterDataUpload.Edit_Record(TC043_CampusMasterDataUpload.java:107)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- Edit_Record -->
</testsuite> <!-- Campus Master Data Upload -->
