<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="OSO-DTP-057" name="Attendance Verify" tests="4" failures="1" timestamp="20 Nov 2017 07:28:58 GMT" time="140.144" errors="0">
  <testcase name="Login" time="2.28" classname="Module.ESS.LeaveandAttendance.LeaveApplication.TC012_AttendanceVerify"/>
  <testcase name="TargetPage" time="86.555" classname="Module.ESS.LeaveandAttendance.LeaveApplication.TC012_AttendanceVerify"/>
  <testcase name="VerifyAttendanceApprove" time="15.957" classname="Module.ESS.LeaveandAttendance.LeaveApplication.TC012_AttendanceVerify">
    <skipped/>
  </testcase> <!-- VerifyAttendanceApprove -->
  <testcase name="VerifyAttendanceReject" time="21.97" classname="Module.ESS.LeaveandAttendance.LeaveApplication.TC012_AttendanceVerify">
    <failure type="java.lang.AssertionError" message="Attendance not rejected">
      <![CDATA[java.lang.AssertionError: Attendance not rejected
	at Module.ESS.LeaveandAttendance.LeaveApplication.TC012_AttendanceVerify.VerifyAttendanceReject(TC012_AttendanceVerify.java:105)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- VerifyAttendanceReject -->
</testsuite> <!-- Attendance Verify -->
