<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="OSO-DTP-057" name="ESS.LeaveandAttendance.LeaveApplication.TC008_RosterDefinition" tests="5" failures="0" timestamp="6 Oct 2017 07:37:19 GMT" time="0.581" errors="5">
  <testcase name="TargetPage" time="0.000" classname="ESS.LeaveandAttendance.LeaveApplication.TC008_RosterDefinition">
    <error type="java.lang.Throwable" message="Method TC008_RosterDefinition.TargetPage()[pri:0, instance:ESS.LeaveandAttendance.LeaveApplication.TC008_RosterDefinition@eff876] depends on not successfully finished methods in group &quot;RDLogin&quot;">
      <![CDATA[java.lang.Throwable: Method TC008_RosterDefinition.TargetPage()[pri:0, instance:ESS.LeaveandAttendance.LeaveApplication.TC008_RosterDefinition@eff876] depends on not successfully finished methods in group "RDLogin"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1040)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:391)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- TargetPage -->
  <testcase name="DefineRoster" time="0.000" classname="ESS.LeaveandAttendance.LeaveApplication.TC008_RosterDefinition">
    <error type="java.lang.Throwable" message="Method TC008_RosterDefinition.DefineRoster(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:ESS.LeaveandAttendance.LeaveApplication.TC008_RosterDefinition@eff876] depends on not successfully finished methods in group &quot;RDSearchRecord&quot;">
      <![CDATA[java.lang.Throwable: Method TC008_RosterDefinition.DefineRoster(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:ESS.LeaveandAttendance.LeaveApplication.TC008_RosterDefinition@eff876] depends on not successfully finished methods in group "RDSearchRecord"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1040)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:391)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- DefineRoster -->
  <testcase name="SearchRecord" time="0.000" classname="ESS.LeaveandAttendance.LeaveApplication.TC008_RosterDefinition">
    <error type="java.lang.Throwable" message="Method TC008_RosterDefinition.SearchRecord()[pri:0, instance:ESS.LeaveandAttendance.LeaveApplication.TC008_RosterDefinition@eff876] depends on not successfully finished methods in group &quot;RDTargetPage&quot;">
      <![CDATA[java.lang.Throwable: Method TC008_RosterDefinition.SearchRecord()[pri:0, instance:ESS.LeaveandAttendance.LeaveApplication.TC008_RosterDefinition@eff876] depends on not successfully finished methods in group "RDTargetPage"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1040)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:391)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- SearchRecord -->
  <testcase name="EditDefinedRoster" time="0.000" classname="ESS.LeaveandAttendance.LeaveApplication.TC008_RosterDefinition">
    <error type="java.lang.Throwable" message="Method TC008_RosterDefinition.EditDefinedRoster()[pri:0, instance:ESS.LeaveandAttendance.LeaveApplication.TC008_RosterDefinition@eff876] depends on not successfully finished methods in group &quot;RDTargetPage&quot;">
      <![CDATA[java.lang.Throwable: Method TC008_RosterDefinition.EditDefinedRoster()[pri:0, instance:ESS.LeaveandAttendance.LeaveApplication.TC008_RosterDefinition@eff876] depends on not successfully finished methods in group "RDTargetPage"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1040)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:391)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- EditDefinedRoster -->
  <testcase name="Login" time="0.581" classname="ESS.LeaveandAttendance.LeaveApplication.TC008_RosterDefinition">
    <error type="org.testng.SkipException" message="Not Executed this test case">
      <![CDATA[org.testng.SkipException: Not Executed this test case
	at ESS.LeaveandAttendance.LeaveApplication.TC008_RosterDefinition.Login(TC008_RosterDefinition.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:391)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- Login -->
</testsuite> <!-- ESS.LeaveandAttendance.LeaveApplication.TC008_RosterDefinition -->
